import type { ReactNode } from 'react';

import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import '@/app/globals.css';
import { Toaster } from '@/components/ui/sonner';

const montserrat = Montserrat({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-montserrat',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
    title: 'SLR Membership',
    description: 'Generated by SLR Membership'
};

const Layout = ({ children }: Readonly<{ children: ReactNode }>) => {
    return (
        <html suppressHydrationWarning lang='en'>
            <body
                suppressHydrationWarning
                className={`${montserrat.variable} text-foreground overscroll-none bg-[#131619] antialiased`}>
                {children}
                <Toaster />
            </body>
        </html>
    );
};

export default Layout;
